### ISSUE TITLE
Support timeout on fetch requests

### ISSUE THREAD

**Issue by ramboz** [adobe/helix-fetch#1]
**Is your feature request related to a problem? Please describe.**
Running multiple fetch requests in parallel may end up causing denial-of-service attacks if they are long-lived.

**Describe the solution you'd like**
Regular XHR requests support a timeout that will fail the request after a specific amount of time.
There is currently no clear spec for it in the fetch API, but some discussion around it exist (see links below)

Would be great to have a first draft implementation in the library to offer a decent enough implementation until the spec is finalized.

**Describe alternatives you've considered**
This can alternatively be implemented consumer-side by using timeouts and promises, and rejecting the promise before the request ends, but the socket is still left open until the fetch actually finishes so it doesn't fully removes the issue

**Additional context**
See:
- https://github.com/whatwg/fetch/issues/20
- https://github.com/whatwg/fetch/issues/179
- https://github.com/whatwg/fetch/issues/180

**Comment by stefan-guggisberg** [comment]
supported in `v1.1.0`
