### ISSUE TITLE
Persistent ERR_HTTP2_INVALID_SESSION errors when network infrastructure changes

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-fetch#103]
**Description**
It seems that requesting a http/2 server starts to fail, if the DNS of the host changes to a server that doesn't support http/2.
Looking at the code in fetch-h2, it seems that the http/2 sessions are cached by hostname and not by ip.

**To Reproduce**

not so trivial...

**Expected behavior**
Ideally, the client wouldn't notice the switch and the request is internally restarted.

**Comment by stefan-guggisberg** [comment]
underlying `fetch-h2` issue: https://github.com/grantila/fetch-h2/issues/88
