### ISSUE TITLE
query parameter support

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-fetch#11]
**Is your feature request related to a problem? Please describe.**
I think it would benefit to add querystring support; so every piece of code that uses query strings doesn't have to write its own implementation of appending them to the URL. 

**Describe the solution you'd like**
just use URL.searchParams code

**Describe alternatives you've considered**
query-string library

**Comment by MarquiseRosier** [comment]
@stefan-guggisberg @trieloff whatdya guys think about this? I need it for helix-embed; as that will begin using helix-fetch!

**Comment by trieloff** [comment]
I'd rather stay true to the spec, which does not have a `qs` option, but instead use a proper `URL` with `URLSearchParams` set. https://nodejs.org/api/url.html#url_class_urlsearchparams has an example.

We should include that in our documentation and test that the `url` can be specified using the `URL` type.

**Comment by stefan-guggisberg** [comment]
> I'd rather stay true to the spec, which does not have a `qs` option, but instead use a proper `URL` with `URLSearchParams` set. https://nodejs.org/api/url.html#url_class_urlsearchparams has an example.
> 
> We should include that in our documentation and test that the `url` can be specified using the `URL` type.

@trieloff  While I generally like the idea it is not soec-compliant: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch

The spec mandates a plain string. We could 'extend' it though, by also supporting a `URL` instance. 

WDYT?

**Comment by MarquiseRosier** [comment]
^^ if we're going to 'extend' than we might as well do the option that'll lead to less work for developers?

**Comment by tripodsan** [comment]
> The spec mandates a plain string. We could 'extend' it though, by also supporting a URL instance.

I don't think it's a super improvement of writing `fetch(url.href)` over `fetch(url)`.
also, the _spec_ also allows passing in a `Request` object.

**Comment by stefan-guggisberg** [comment]
> ^^ if we're going to 'extend' than we might as well do the option that'll lead to less work for developers?

I agree, good point.

**Comment by trieloff** [comment]
I'd say: stay close to the spec, and put the convenience helpers elsewhere.
