### ISSUE TITLE
v2: automatically set content-type based on request body

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-fetch#122]
**Is your feature request related to a problem? Please describe.**
node-fetch automatically sets the `content-type` header, based on the body given to `new Response()`:
https://github.com/node-fetch/node-fetch/blob/6ee9d3186f8b4bdc4288ccf92f0a776aa17644ae/src/request.js#L72

It would be convenient to do the same in helix-fetch.

**Comment by stefan-guggisberg** [comment]
`Request` or `Response`?

`helix-fetch` does that already in the `Request` constructor: https://github.com/adobe/helix-fetch/blob/main/src/fetch/request.js#L96-L107
