### ISSUE TITLE
v2: detect nock and disable h2 automatically?

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-fetch#124]
Would this be possible? It would reduce our required boilerplate quite a bit.

**Comment by stefan-guggisberg** [comment]
There's `nock.isActive()` but that would mean adding `nock` as a production dependency, something I'd like to avoid.

**Comment by stefan-guggisberg** [comment]
After some more digging I found a way:

1, detect if `mocha` is running based on the existence of certain global functions (`it`, `describe`, `before` etc)
2, try requiring `nock`
3. call `nock.isActive`

IMO it would be a nasty hack, adding hidden magic and in general a bad practice to write test aware production code.

Closing.
