### ISSUE TITLE
v2: setting non string response headers should coerce value to string

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-fetch#125]
**Description**
I didn't verify this, but based on the code, the following is possible:

```
new Response('foo', {
  headers: {
    bar: [ 1, 2, 3],
  }
});
```

according to https://fetch.spec.whatwg.org/#dom-headers-set, this should throw an error.

**Comment by stefan-guggisberg** [comment]
I tested the following in Chrome, Safari, Firefox and with `node-fetch`:

```javascript
  const hdrs = new Headers();
  const val = [1,2,3];
  hdrs.set('a', val);
  assert(hdrs.get('a') === val.toString());
```

They all don't throw but coerce the value into a string.  `helix-fetch` should do the same.

**Comment by tripodsan** [comment]
@trieloff FYI
