### ISSUE TITLE
querystrings parameters permit array values

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-fetch#13]
allow something like 

qs: {
  name: ['foo', 'bar']
}

**Comment by stefan-guggisberg** [comment]
@MarquiseRosier Do you have a concrete use case? AFAIK there's no standard way of encoding a query parameter with an array value. Since a server would need to support the non-standardised serialisation format I question the usefulness of such a feature.

**Comment by MarquiseRosier** [comment]
@stefan-guggisberg I believe @tripodsan  wanted this feature baked into the last PR!

**Comment by stefan-guggisberg** [comment]
@MarquiseRosier Thanks for the clarification.

@tripodsan See my earlier comment.  I question the usefulness of this feature since the encoding of a query parameter with an array value is not standardised. Did I miss something or do you have a concrete use case for this?

**Comment by tripodsan** [comment]
> the encoding of a query parameter with an array value is not standardised.

yes, the value is just repeated... eg:

```
$ curl -X GET "https://httpbin.org/get?name=foo&name=bar" -H "accept: application/json"
{
  "args": {
    "name": [
      "foo",
      "bar"
    ]
  },
  "headers": {
    "Accept": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.64.1",
    "X-Amzn-Trace-Id": "Root=1-5e83f2ae-9dfb195608792b6f69abbda9"
  },
  "origin": "113.42.254.58",
  "url": "https://httpbin.org/get?name=foo&name=bar"
}
```

This is achieved automatically then calling `https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/append`:

```js
$ node
> const url = new URL('https://httbin.org');
> url.searchParams.append('name', 'foo');
> url.searchParams.append('name', 'bar');
> url.href
'https://httbin.org/?name=foo&name=bar'
```

**Comment by stefan-guggisberg** [comment]
ok, sounds reasonable.
