### ISSUE TITLE
Support Body.formData

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-fetch#149]
Needed for adobe/helix-logging#450 - URL encoded form data is needed, multipart form data is optional.

**Comment by stefan-guggisberg** [comment]
Workaround for the mentioned use case:

```javascript
if (/^application\/x-www-form-urlencoded/.test(request.headers.get('content-type'))) {
  const data = new URLSearchParams(await request.text());
```

Supporting `body.formData()` (returning a spec-compliant implementation) would require adding another dependency (increasing install size) or implementing FormData from scratch. Neither seems justified given the trivial workaround. I'd therefore rather not support it at this time.

BTW: `node-fetch` doesn't support it: https://github.com/node-fetch/node-fetch#interface-body.
`whatwg-fetch` doesn't seem to support it on node either.

**Comment by trieloff** [comment]
Ok
