### ISSUE TITLE
Any chance of supporting an async cache api for custom implementations ?

### ISSUE THREAD

**Issue by cameronbraid** [adobe/helix-fetch#176]
I'd like to use your api however I need an async based cache interface.  

Is this something you would consider adding ?

It looks like your cache api isn't exposed so it seems like a feasible option

**Comment by stefan-guggisberg** [comment]
Thanks for your interest. Cache pluggability and support for an async Cache API is currently not planned. 

However, you should be able to implement the fetch cache in a  tiny `helix-fetch` wrapper, similar to https://github.com/adobe/helix-fetch/blob/main/src/fetch/index.js#L257-L276. You can disable `helix-fetch`s internal cache by either setting the  fetch option `cache: 'no-store'` or the context option `maxCacheSize: 0`.
