### ISSUE TITLE
timeoutSignal may keep node process alive

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-fetch#185]
**Description**
In my test suite, I'm using `@adobe/helix-fetch` and its `timeoutSignal` to abort requests that exceed 20 seconds. If I run one of my tests isolated (with `npx mocha -g '...'`, I notice that the test succeeds, but the node process keeps running for about 20 seconds. If I avoid the call to `timeoutSignal`, the node process terminates immediately after executing the test.

**To Reproduce**
1. Create a test that fetches some page with `@adobe/helix-fetch`
2. Optionally, `nock` that request, so it executes even faster
3. Add a `timeoutSignal` with a timeout of at least 20 seconds
4. Run the test isolated with `npx mocha -g '...'`, the process will appear to hang after the test has executed.

Interestingly, this behaviour cannot be reproduced when running the test with `it.only`.

**Expected behavior**
Node process should exit when the test has been executed.

**Version:**
2.2.1

**Additional context**

**Comment by dominique-pfister** [comment]
After further consideration, going with `--exit` in my tests seems the better solution.

**Comment by tripodsan** [comment]
> After further consideration, going with `--exit` in my tests seems the better solution.

could this also affect the termination of a action/function ? or be potential memory leak under high concurrency ?

**Comment by stefan-guggisberg** [comment]
why would there be a memory leak?

it's not a fetch-specific issue. a `setTimeout` which hasn't been triggered yet, open socket etc all prevent node process from exiting.

**Comment by stefan-guggisberg** [comment]
The `signal` is user-provided and not part of the fetch spec. 

I'll change the `timeoutSignal(ms)` non-spec convenience method to return a timeout signal which can be cleared by the user, e.g. 

```javascript
  const { fetch, timeoutSignal, AbortError } = require('@adobe/helix-fetch');

  const signal = timeoutSignal(1000);
  try {
    const resp = await fetch('https://httpbin.org/json', { signal });
    const jsonData = await resp.json();
  } catch (err) {
    if (err instanceof AbortError) {
      console.log('fetch timed out after 1s');
    }
  } finally {
    // avoid pending timers which prevent node process from exiting
    signal.clear();
  }
```

For comparison, the spec compliant way would be 
```javascript
  const { fetch, AbortController, AbortError } = require('@adobe/helix-fetch');

  const controller = new AbortController();
  const timerId = setTimeout(() => controller.abort(), 1000);
  const { signal } = controller;

  try {
    const resp = await fetch('https://httpbin.org/json', { signal });
    const jsonData = await resp.json();
  } catch (err) {
    if (err instanceof AbortError) {
      console.log('fetch timed out after 1s');
    }
  } finally {
    // avoid pending timers which prevent node process from exiting
    clearTimeout(timerId);
  }
```
