### ISSUE TITLE
node will crash when use AbortController

### ISSUE THREAD

**Issue by ranbochen** [adobe/helix-fetch#238]
**Description**
I use AbortController to control fetch timeout.
AbortError catched but nodejs still exit.
I tested it, not every timeout will crash the process.
Do I need to try-cathc the controller.abort() call?
I used it according to this example: [https://github.com/adobe/helix-fetch#specify-a-timeout-for-a-fetch-operation](url)

**Expected behavior**
process do not crash

**Version:**
"@adobe/helix-fetch": "^3.0.0"
nodejs v16.13.0

**Log:**
```
[2022/1/1 22:01:36][error] fetch data error: AbortError - fetching: The operation was aborted.
[2022/1/1 22:01:36][info] retry after 10s
D:\proj\node_modules\@adobe\helix-fetch\src\core\h2.js:235
      reject(new RequestAbortedError());
             ^
RequestAbortedError
    at EventEmitter.onAbortSignal (D:\proj\node_modules\@adobe\helix-fetch\src\core\h2.js:235:14)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.emit (node:domain:475:12)
    at AbortSignal.dispatchEvent (D:\proj\node_modules\@adobe\helix-fetch\src\fetch\abort.js:67:41)
    at AbortSignal.fire (D:\proj\node_modules\@adobe\helix-fetch\src\fetch\abort.js:72:10)
    at AbortController.abort (D:\proj\node_modules\@adobe\helix-fetch\src\fetch\abort.js:137:39)
    at Timeout._onTimeout (D:\proj\src\utils\fetch.ts:44:49)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Code:**
```
const defaultTimeout = 30 * 1000
const defaultFetch = newFetchContext()
interface TimeoutRequestOptions extends RequestOptions {
    timeout?: number
}
export async function fetchWithTimeout(url: string, options: TimeoutRequestOptions = {}): Promise<Response> {
    const controller = new helixFetch.AbortController()
    const timerId = setTimeout(() => controller.abort(), options.timeout ? options.timeout : defaultTimeout)

    try {
        options.signal = controller.signal
        const response = await defaultFetch.fetch(url, options)
        return response
    } catch (err) {
        if (err.name === 'RequestAbortedError') {
            err = new Error('Fetch Timeout')             **<-- NOT HAPPEN.** 
        }
        throw err
    } finally {
        clearTimeout(timerId)
    }
}

call stack this:
while(true) {
    try {
        try {
            fetchWithTimeout(someUrl)
        } catch(e) {
            e.message = `fetching: ${e.message}`
            throw e
        }
    } catch(err) {
        logger.error('fetch data error: %s - %s', err.name, err.message)
        logger.info('retry after 10s')
        sleep(10s)
    }

    sleep(someTime)
}
```

**Comment by stefan-guggisberg** [comment]
Your code example is incomplete and doesn't really make sense TBH.

Here's a simple self-contained test which uses `AbortController` according to this example: https://github.com/adobe/helix-fetch#specify-a-timeout-for-a-fetch-operation

```javascript
const { fetch, reset, AbortController, AbortError } = require('@adobe/helix-fetch').noCache();

const timeout = 50;
const url = 'https://httpbin.org/json';
const controller = new AbortController();
const timerId = setTimeout(() => controller.abort(), timeout);
const { signal } = controller;

const main = async () => {
  let count = 100;
  while (count-- > 0) {
    try {
      console.log(`fetching ${url}`);
      const resp = await fetch(url, { signal });
      console.log(`successfully fetched ${url}`);
    } catch (err) {
      if (err instanceof AbortError) {
        console.log(`fetch timed out after ${timeout}ms`);
      }
    } finally {
      // avoid pending timers which prevent node process from exiting
      clearTimeout(timerId);
    }
  }
}

main()
  .catch(console.err)
  .finally(reset);
```

I have tested it with node v16.13.0 and it works for me as expected.

**Comment by ranbochen** [comment]
I have do some test ,and it's not crash every time.
Test case is ok, but under some condition, Log says fetch reject twice, so nodejs crashed.

In my app, i fetch data for about 10K times per day. 
Timeout happens a lot, app crashes about once every two or three days.

**Comment by ranbochen** [comment]
@stefan-guggisberg 
I read the code of helix-fetch. 
looks like "Requestabortederror" should NEVER throw to app code scope, 
helix-fetch always catch it and translate to "AbortError" like this:
```
    if (err instanceof RequestAbortedError) {
      throw new AbortError('The operation was aborted.');
    }
```
but it does throw out, so there must be something wrong in strange ways

**Comment by ranbochen** [comment]
> > @stefan-guggisberg I read the code of helix-fetch. looks like "Requestabortederror" should NEVER throw to app code scope, helix-fetch always catch it and translate to "AbortError" like this:
> 
> yes, correct.
> 
> > but it does throw out, so there must be something wrong in strange ways
> 
> what makes you think that `await fetch(...)` throws the `RequestAbortedError`?

crash log shows it's cased by "RequestAbortedError"
I tried to reproduce and fix the issue, but failed.
it's a very strange error, I read the code carefully but have no idea why it happened!

**Comment by stefan-guggisberg** [comment]
Do you consume the response body within a try/catch? Note that the AbortError may also be thrown while streaming the response body, e.g.

```javascript
let resp;
try {
  resp = await fetch(url, { signal });
} catch (err) {
  // handle error
}
const body = await resp.body();  // AbortError or else may be thrown here
```

**Comment by stefan-guggisberg** [comment]
Note that as of Node v16 unhandled promise rejections trigger `process.exit(1)` rather than just printing a warning on the console. 

You can prevent the process termination by a adding a global `unhandledRejection` handler, e.g.:

```javascript
process.on('unhandledRejection', (reason, promise) => {
  console.log('Unhandled Rejection at:', promise, 'reason:', reason);
});
```
