### ISSUE TITLE
AbortController, AbortError not fully usable from TypeScript

### ISSUE THREAD

**Issue by mtaran** [adobe/helix-fetch#250]
**Description**
The .d.ts file specifies some exported symbols as types instead of as values, but users need to use those symbols as values. Specifically, at least:

 * Example code in the README includes `if (err instanceof AbortError)` but this doesn't compile in TypeScript since currently the .d.ts exports AbortError as an `interface` instead of as a `declare class`
 * To use the aborting (early cancellation) functionality, a user needs to create an AbortController but this is not possible in TypeScript since the current .d.ts exports the AbortController as a `type` instead of as a `declare class`

**Comment by stefan-guggisberg** [comment]
Thanks for reporting this issue. The `.d.ts` files are solely provided for convenience (e.g. IDE code completion). I am not a TypeScript expert and TS support wasn't a goal. However I'll try to fix the DTS as sugegsted.

**Comment by mtaran** [comment]
Oh, I was going to send a PR with some fixes, I just saw that the PR guide said to file an issue first (and then I ran out of time yesterday to send the PR itself).

If you're not too invested in the specific form of the .d.ts files I may send some additional further improvements in the future. Would you still need me to file issues for those beforehand or would it be fine to send the PRs directly?

Thanks!

**Comment by stefan-guggisberg** [comment]
@mtaran I just merged a fixed `.d.ts` and I am going to close this issue. 

If you find other issues in the  `.d.ts` or have suggestions for improvement please file a new issue.  

PRs are of course welcome. Pairing PRs with issues helps tracking changes.
