### ISSUE TITLE
Cancelling a POST with a string body generates an asynchronous uncaught error

### ISSUE THREAD

**Issue by mtaran** [adobe/helix-fetch#251]
**Description**
When doing a POST request with a string passed in as the `body`, helix-fetch internally converts it to a Readable stream. When an ongoing request is aborted, the body stream is destroyed, sending along an error. The code that normalizes the `body` to a Readable stream adds a handler for the 'error' event, but currently does so *only when the original `body` was a Readable stream*. So if the original `body` is e.g. a string, then the Readable stream version of it will not have an error handler, and aborting the request will cause it to emit an 'error' event which is never caught, causing e.g. tests of the functionality to fail.

**To Reproduce**
1. run a test where you perform a POST fetch with string data
2. abort the request
3. get an error about an uncaught error, which happens after the test has already finished (this is because destroying the Readable stream schedules the error event on the next tick)

**Expected behavior**
The error should be caught (or not emitted at all).

**Comment by stefan-guggisberg** [comment]
Great catch! Thanks for filing this issue and the concise description.
