### ISSUE TITLE
Potential problems with timeout

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-fetch#27]
**Description**
Looking at https://github.com/grantila/fetch-h2/blob/master/lib/context.ts#L413, I don't see that there is a connect-timeout passed to the socket connection... AFAICS, the timeout is implemented as promise race. which leads to hanging sockets, if the connection is slow. so my tests fail (> 2000ms) sometimes, although I specify a timeout of 20ms.

This should be clarified.

**Comment by stefan-guggisberg** [comment]
@tripodsan Not sure I understand the problem. Can you provide a test which demonstrates the issue?

**Comment by tripodsan** [comment]
> Can you provide a test which demonstrates the issue?

not right now...

What I suspect is, that the connect timeout is not configurable via the `timeout` option. i.e. if you have a slow network, where connection to the host is slow, the timeout option is not honoured.

so the tests in helix-pipeline that check if a short timeout works, fail if the connect takes longer than 2s.

**Comment by stefan-guggisberg** [comment]
Thanks for the clarification, now I understand the problem. I can confirm that the `timeout` option passed in the `fetch` call   has no effect regarding the connection establishment, i.e. the `tls.connect` call is not  aborted after `timeout` ms.

I am looking into it.

**Comment by stefan-guggisberg** [comment]
Underlying `fetch-h2` issue: https://github.com/grantila/fetch-h2/issues/99

**Comment by stefan-guggisberg** [comment]
fixed in v2 (75cbcbe)
